#pragma once

static const char AUDIO_WEB_PAGE[] =
    "<!doctype html><html lang='pt-BR'><head>"
    "<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>Áudio ESP32</title><style>"
    "body{font:16px system-ui;max-width:34rem;margin:2rem auto;padding:0 1rem;background:#101827;color:#eef2ff}"
    "main{background:#18243a;border-radius:16px;padding:1.25rem;box-shadow:0 12px 32px #0005}"
    "button,input{font:inherit;margin:.5rem 0}button{background:#38bdf8;border:0;border-radius:9px;padding:.75rem 1rem;color:#082f49;font-weight:700}"
    "button:disabled{opacity:.45}progress{width:100%;height:1.1rem}small{color:#a5b4fc}pre{white-space:pre-wrap}"
    "</style></head><body><main><h1>Enviar gravação</h1>"
    "<p><input id='audio' type='file' accept='audio/*' capture='user'></p>"
    "<p id='details'><small>Escolha ou grave um áudio no celular.</small></p>"
    "<progress id='progress' value='0' max='100'></progress><p>"
    "<button id='send' disabled>Enviar pela ESP32</button></p><pre id='result'></pre>"
    "</main><script>"
    "const input=document.querySelector('#audio'),button=document.querySelector('#send'),"
    "progress=document.querySelector('#progress'),result=document.querySelector('#result'),details=document.querySelector('#details');"
    "input.onchange=()=>{const f=input.files[0];button.disabled=!f;progress.value=0;result.textContent='';"
    "details.textContent=f?`${f.name} · ${f.type||'tipo desconhecido'} · ${f.size} bytes`:'Escolha um áudio.'};"
    "button.onclick=()=>{const f=input.files[0];if(!f)return;button.disabled=true;result.textContent='Enviando…';"
    "const xhr=new XMLHttpRequest();xhr.open('POST','/api/audio/input');"
    "xhr.setRequestHeader('Content-Type',f.type||'audio/webm');"
    "xhr.setRequestHeader('X-Audio-Filename',f.name.replace(/[^ -~]/g,'_'));"
    "xhr.upload.onprogress=e=>{if(e.lengthComputable)progress.value=Math.round(e.loaded*100/e.total)};"
    "xhr.onload=()=>{result.textContent=`HTTP ${xhr.status}\n${xhr.responseText}`;button.disabled=false};"
    "xhr.onerror=()=>{result.textContent='Falha de rede durante o upload.';button.disabled=false};"
    "xhr.onabort=()=>{result.textContent='Upload cancelado.';button.disabled=false};xhr.send(f)};"
    "</script></body></html>";
